name: "Build and Deploy Tenant Service to ECS"

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'tenant-service/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: flowcore-tenant-service
  ECS_SERVICE: tenant-service
  ECS_CLUSTER: flowcore-cluster

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Grant execute permissions for mvnw
        run: chmod +x mvnw
      - name: Run tests
        run: ./mvnw clean test

  build-and-deploy:
    name: Build and Deploy to ECS
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/master' && 'production') || 'dev' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin  '
          java-version: '17'
          cache: 'maven'
      - name: Grant execute permissions for mvnw
        run: chmod +x mvnw
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/devops-role
          role-session-name: devops-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
          mask-password: false
      - name: Build and push Docker image to AWS ECR 
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tenant-service:latest .
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/tenant-service:latest

    #  - name: Build and push Docker image to Docker Hub
    #    uses: docker/build-push-action@v6
    #    with:
    #      context: .
    #      file: Dockerfile
    #      push: true
    #      tags: ${{ secrets.DOCKER_USERNAME }}/tenant-service:latest
    #      username: ${{ secrets.DOCKER_USERNAME }}
    #      password: ${{ secrets.DOCKER_PASSWORD }}
    